const data = [
    {
        id: '1',
        maintenanceId: "M001",
        lastMaintenanceYear: '2020',
        HouseBuiltYear: '2000',
        email: "user1@example.com",
        sustainabilityScore: 75,
        date: "2024-09-05",
        status: 'Completed',
        address: " Main St, City A",
        buildingNo: 'A-123',
        buildingType: "Residential",
        zipCode: "10001"
    },
    {
        id: '2',
        maintenanceId: "M002",
        lastMaintenanceYear: '2020',
        HouseBuiltYear: '2000',
        email: "user2@example.com",
        sustainabilityScore: 85,
        date: "2024-09-04",
        status: 'ongoing',
        address: "Park Ave, City B",
        buildingNo: 'B-456',
        buildingType: "Commercial",
        zipCode: "10002"
    },
    {
        id: '3',
        maintenanceId: "M003",
        lastMaintenanceYear: '2020',
        HouseBuiltYear: '2000',
        email: "user3@example.com",
        sustainabilityScore: 65,
        date: "2024-09-03",
        status: 'ongoing',
        address: "Elm St, City C",
        buildingNo: 'C-789',
        buildingType: "Industrial",
        zipCode: "10003"
    },
    {
        id: '4',
        maintenanceId: "M004",
        lastMaintenanceYear: '2020',
        HouseBuiltYear: '2000',
        email: "user4@example.com",
        sustainabilityScore: 90,
        date: "2024-09-02",
        status: 'Completed',
        address: "Maple St, City D",
        buildingNo: 'D-101',
        buildingType: "Residential",
        zipCode: "10004"
    },
    {
        id: '5',
        maintenanceId: "M005",
        lastMaintenanceYear: '2020',
        HouseBuiltYear: '2000',
        email: "user5@example.com",
        sustainabilityScore: 80,
        date: "2024-09-01",
        status: 'ongoing',
        address: "202 Oak St, City E",
        buildingNo: 'E-202',
        buildingType: "Commercial",
        zipCode: "10005"
    },
    {
        id: '6',
        maintenanceId: "M006",
        lastMaintenanceYear: '2020',
        HouseBuiltYear: '2000',
        email: "user1@example.com",
        sustainabilityScore: 75,
        date: "2024-09-05",
        status: 'Completed',
        address: " Main St, City A",
        buildingNo: 'A-123',
        buildingType: "Residential",
        zipCode: "10001"
    },
    {
        id: '7',
        maintenanceId: "M007",
        lastMaintenanceYear: '2020',
        HouseBuiltYear: '2000',
        email: "user2@example.com",
        sustainabilityScore: 85,
        date: "2024-09-04",
        status: 'ongoing',
        address: "Park Ave, City B",
        buildingNo: 'B-456',
        buildingType: "Commercial",
        zipCode: "10002"
    },
    {
        id: '8',
        maintenanceId: "M008",
        lastMaintenanceYear: '2020',
        HouseBuiltYear: '2000',
        email: "user3@example.com",
        sustainabilityScore: 65,
        date: "2024-09-03",
        status: 'Completed',
        address: "Elm St, City C",
        buildingNo: 'C-789',
        buildingType: "Industrial",
        zipCode: "10003"
    },
    {
        id: '9',
        maintenanceId: "M009",
        lastMaintenanceYear: '2020',
        HouseBuiltYear: '2000',
        email: "user4@example.com",
        sustainabilityScore: 90,
        date: "2024-09-02",
        status: 'Completed',
        address: "Maple St, City D",
        buildingNo: 'D-101',
        buildingType: "Residential",
        zipCode: "10004"
    },
    {
        id: '10',
        maintenanceId: "M010",
        lastMaintenanceYear: '2020',
        HouseBuiltYear: '2000',
        email: "user5@example.com",
        sustainabilityScore: 80,
        date: "2024-09-01",
        status: 'ongoing',
        address: "202 Oak St, City E",
        buildingNo: 'E-202',
        buildingType: "Commercial",
        zipCode: "10005"
    },
    {
        id: '11',
        maintenanceId: "M011",
        lastMaintenanceYear: '2020',
        HouseBuiltYear: '2000',
        email: "user1@example.com",
        sustainabilityScore: 75,
        date: "2024-09-05",
        status: 'ongoing',
        address: " Main St, City A",
        buildingNo: 'A-123',
        buildingType: "Residential",
        zipCode: "10001"
    },
    {
        id: '12',
        maintenanceId: "M012",
        lastMaintenanceYear: '2020',
        HouseBuiltYear: '2000',
        email: "user2@example.com",
        sustainabilityScore: 85,
        date: "2024-09-04",
        status: 'Completed',
        address: "Park Ave, City B",
        buildingNo: 'B-456',
        buildingType: "Commercial",
        zipCode: "10002"
    },
    {
        id: '13',
        maintenanceId: "M013",
        lastMaintenanceYear: '2020',
        HouseBuiltYear: '2000',
        email: "user3@example.com",
        sustainabilityScore: 65,
        date: "2024-09-03",
        status: 'ongoing',
        address: "Elm St, City C",
        buildingNo: 'C-789',
        buildingType: "Industrial",
        zipCode: "10003"
    },
    {
        id: '14',
        maintenanceId: "M014",
        lastMaintenanceYear: '2020',
        HouseBuiltYear: '2000',
        email: "user4@example.com",
        sustainabilityScore: 90,
        date: "2024-09-02",
        status: 'ongoing',
        address: "Maple St, City D",
        buildingNo: 'D-101',
        buildingType: "Residential",
        zipCode: "10004"
    },
    {
        id: '15',
        maintenanceId: "M015",
        lastMaintenanceYear: '2020',
        HouseBuiltYear: '2000',
        email: "user5@example.com",
        sustainabilityScore: 80,
        date: "2024-09-01",
        status: 'Completed',
        address: "202 Oak St, City E",
        buildingNo: 'E-202',
        buildingType: "Commercial",
        zipCode: "10005"
    }
  ];
export default data;