const reqdata = [
    {
        id: '1',
        maintenanceId: "M001",
        RequestId: '514683',
        email: "user1@example.com",
        date: "2024-09-05",
        status: 'Accepted',
        address: " Main St, City A",
    },
    {
        id: '2',
        maintenanceId: "M002",
        RequestId: '134570',
        email: "user2@example.com",
        date: "2024-09-04",
        status: 'closed',
        address: "Park Ave, City B",
    },
    {
        id: '3',
        maintenanceId: "M003",
        RequestId: '544076',
        email: "user3@example.com",
        date: "2024-09-03",
        status: 'Pending',
        address: "Elm St, City C",
    },
    {
        id: '4',
        maintenanceId: "M004",
        RequestId: '123456',
        email: "user4@example.com",
        date: "2024-09-02",
        status: 'Rejected',
        address: "Maple St, City D",
    },
    {
        id: '5',
        maintenanceId: "M005",
        RequestId: '789012',
        email: "user5@example.com",
        date: "2024-09-01",
        status: 'Pending',
        address: "202 Oak St, City E",
    },
    {
        id: '6',
        maintenanceId: "M006",
        RequestId: '345678',
        email: "user1@example.com",
        date: "2024-09-05",
        status: 'closed',
        address: " Main St, City A",
    },
    {
        id: '7',
        maintenanceId: "M007",
        RequestId: '901234',
        email: "user2@example.com",
        date: "2024-09-04",
        status: 'closed',
        address: "Park Ave, City B",
    },
    {
        id: '8',
        maintenanceId: "M008",
        RequestId: '567890',
        email: "user3@example.com",
        date: "2024-09-03",
        status: 'Accepted',
        address: "Elm St, City C",
    },
    {
        id: '9',
        maintenanceId: "M009",
        RequestId: '135791',
        email: "user4@example.com",
        date: "2024-09-02",
        status: 'Accepted',
        address: "Maple St, City D",
    },
    {
        id: '10',
        maintenanceId: "M010",
        RequestId: '357913',
        email: "user5@example.com",
        date: "2024-09-01",
        status: 'Pending',
        address: "202 Oak St, City E",
    },
    {
        id: '11',
        maintenanceId: "M011",
        RequestId: '579135',
        email: "user1@example.com",
        date: "2024-09-05",
        status: 'Pending',
        address: " Main St, City A",
    },
    {
        id: '12',
        maintenanceId: "M012",
        RequestId: '112233',
        email: "user2@example.com",
        date: "2024-09-04",
        status: 'Accepted',
        address: "Park Ave, City B",
    },
    {
        id: '13',
        maintenanceId: "M013",
        RequestId: '445566',
        email: "user3@example.com",
        date: "2024-09-03",
        status: 'Pending',
        address: "Elm St, City C",
    },
    {
        id: '14',
        maintenanceId: "M014",
        RequestId: '778899',
        email: "user4@example.com",
        date: "2024-09-02",
        status: 'Rejected',
        address: "Maple St, City D",
    },
    {
        id: '15',
        maintenanceId: "M015",
        RequestId: '147082',
        email: "user5@example.com",
        date: "2024-09-01",
        status: 'Accepted',
        address: "202 Oak St, City E",
    }
  ];
export default reqdata;